spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdcm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST
    username: root
    password: 123456pd
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON
  profiles:
    include: configuredata
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
server:
  port: 8081
mybatis:
  mapper-locations: mapper/*.xml
logging:
  level:
    com:
      pd:
        pdcmback:
          mapper: debug

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql





