spring:
  datasource:
    url: jdbc:mysql://8.129.183.247:3306/pdcm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=CST
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON
  profiles:
    include: configuredata

server:
  port: 8081
mybatis:
  mapper-locations: mapper/*.xml
logging:
  level:
    com:
      pd:
        pdcmback:
          mapper: debug

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql





